### ISSUE TITLE
debug mode is not work

### ISSUE THREAD

**Issue by unde4induser** [LordFetznschaedl/CS2InstantDefuse#8]
debug mode is not work, latest release. I set “Debug”: false , but the logs in the console are still spammed!!!!!!

**Comment by LordFetznschaedl** [comment]
Hi @SLAME777 

sorry to hear. Did you restart the server after changing the value to false?

If yes. Then I will look into it

**Comment by LordFetznschaedl** [comment]
Hi @SLAME777 & @Josh-S0 

Issue has been resolved now. Sorry about this.
https://github.com/LordFetznschaedl/CS2InstantDefuse/releases/tag/v1.3.0

The debug message that caused the spamming has been put behind another setting that is disabled by default.

I have now added a new feature as well that if a player without a defuse kit starts defusing and less then 10 seconds are left then additional checks will be done if another player is able to defuse (because he has a defuser)

Regards,
Robert
